[profile.default]
src = "src/v2/utilities"
test = "test"
libs = ["lib"]
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200

remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "@uniswap/v4-core/=lib/v4-core/",
  "@uniswap/v4-hooks-public/=lib/v4-hooks-public/",
  "@uniswap/v4-periphery/=lib/v4-periphery/",
  "permit2/=lib/v4-periphery/lib/permit2/",
]
